todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from todolist import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='home')),
    path('', include('todolist.urls', namespace='todo')),

]

todolist/urls.py
from django.urls import path
from todolist import views

app_name = 'todolist'

urlpatterns = [
    # home page
    path('', views.todo, name='home'),

    path('todo/', views.todo, name='todo'),
    # detail page for a single topic
    path('todo/<int:title_id>', views.single_todo_list, name='single_todo_list'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:title_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:title_id>', views.edit_entry, name='edit_entry'),

]

todolist/models.py
from django.db import models
from django.db.models import CharField
# from django.utils import timezone
from datetime import datetime
# from django.utils.timezone import localtime, now
from django.utils.timezone import utc
import pytz



# Create your models here.



class TodoList(models.Model):
    title = models.CharField(max_length=200)
    completed = models.IntegerField(default=0)

    def __str__(self):
        return self.title[:50]


class TodoItem(models.Model):
    todolist = models.ForeignKey(TodoList, on_delete=models.CASCADE)  #  need the foreign key
    name = models.CharField(max_length=200)  # need for form
    description = models.TextField()  # need for form
    date_created = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField()  # need for form
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.name[:50]

    def days_left(self):
        today = datetime.utcnow().replace(tzinfo=utc)
        today = today.date()
        delta = (self.due_date - today)
        return f'{delta.days}'

todolist/forms.py
from django import forms

from .models import TodoItem, TodoList


## LIST

class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['title', 'completed']
        labels = {'title': 'Please enter a new Topic',
                  'completed': 'Default is set to zero'}


# ENTRY TO THE LIST


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['name', 'description', 'due_date']
        labels = {'name': 'Please enter a new item of this',
                  'description': 'Small blurb about this the item',
                  'due_date': 'Enter a due date Y-M-D'}

todolist/views.py
from django.shortcuts import render, redirect
from .models import TodoList, TodoItem
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import pprint

from .forms import TodoItemForm, TodoListForm

# Create your views here.


def home(request):
    item = TodoList.objects.all()
    return render(request, 'page/home.html', {'item': item})


def todo(request):
    complete_list = TodoList.objects.all()
    context = {'complete_list': complete_list}
    return render(request, 'page/todo.html', context)


## show single list with all the entries

def single_todo_list(request, title_id):
    if request.method == 'POST':
        print('########', request.POST)
        # print('##title ID', title_id)
        r = request.POST.getlist("item_id") # use this getlist, this creates a new name
        # pull items.ids,  and use python code

        for id_in_record in r:
            # # Selecting the record on that list
            todo = TodoItem.objects.get(pk=id_in_record)
            # # modify that specific record to save it
            todo.done = True
            # # saving that item
            todo.save()


    # Select one Item
    single_todo_list = TodoList.objects.get(id=title_id)
    ## todoitem_set
    items_to_that_list = single_todo_list.todoitem_set.order_by('-date_created')
    # send data to the html page this is done with a dictionary
    context = {'single_todo_list': single_todo_list, 'items_to_that_list': items_to_that_list}
    return render(request, 'page/single_todo_list.html', context)
    # return HttpResponse('hi')


def new_topic(request):
    '''Add a new topic'''
    print(request.POST)
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TodoListForm()
    else:
        # POST data submitted; process data.
        form = TodoListForm(data=request.POST)
        # print('####-----#####', form)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todolist:todo'))

    context = {'form': form}
    return render(request, 'page/new_topic.html', context)


def new_entry(request, title_id):
    '''entry for a list'''
    print('GET RESPONSE###########', request.GET)

    todolist = TodoList.objects.get(id=title_id)

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TodoItemForm()
    else:
        # Post data submitted; processed data
        form = TodoItemForm(data=request.POST)
        # print('####-----#####', form)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.todolist = todolist
            new_entry.save()
            return HttpResponseRedirect(reverse('todolist:new_entry', args=[title_id]))
            # return HttpResponse('hi 1 post response')

    context = {'todolist': todolist, 'form': form}
    print('#########', todolist)
    # pprint(context)
    return render(request, 'page/new_entry.html', context)
    # return HttpResponse('hi 2 get response')

def edit_entry(request, entry_id):
    '''edit existing entry'''
    entry = TodoItem.objects.get(id=entry_id)
    topic = entry.names

    if request.method != 'POST':
        # Initial request
        form = TodoItemForm(instance=entry)
    else:
        form = TodoItemForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('todolist:todo', args=[title.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request,  'page/new_entry.html', context)




# submit a form to update the items in the todolist

## when a post request is comming select the record to the database

# then return the thing

# def new_topic(request):
#     """Add a new topic."""
#     if request.method != 'POST':
#         # No data submitted; create a blank form.
#         form = TopicForm()
#     else:
#         # POST data submitted; process data.
#         form = TopicForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('learning_logs:topics'))
#     context = {'form': form}
#     return render(request, 'learning_logs/new_topic.html', context)
#

# @require_POST


# def complete_one_item_todo(request, item_id):
#     # If the method is GET leave the item as it is
#     if request.method != 'POST':
#         return redirect('page/single_todo_list.html')
#     else:

todolist/templates/page/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
<p>
    <a href="{% url 'todolist:todo' %}">All the todo lists</a>

</p>

{% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todolist/templates/page/bootstrap.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Product example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/product/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
  </head>
  <body>
    <nav class="site-header sticky-top py-1">
  <div class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="#">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
    </a>
    <a class="py-2 d-none d-md-inline-block" href="#">Tour</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Product</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Features</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Enterprise</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Support</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Pricing</a>
    <a class="py-2 d-none d-md-inline-block" href="#">Cart</a>
  </div>
</nav>

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">Punny headline</h1>
    <p class="lead font-weight-normal">And an even wittier subheading to boot. Jumpstart your marketing efforts with this example based on Apple’s marketing pages.</p>
    <a class="btn btn-outline-secondary" href="#">Coming soon</a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-primary mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another headline</h2>
      <p class="lead">And an even wittier subheading.</p>
    </div>
    <div class="bg-white shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script></body>
</html>

todolist/templates/page/edit_entry.html
{% extends "page/base.html" %}
{% block content %}
<h3>
    <a href="{% url 'todolist:single_todo_list' todolist.id %}">{{ todolist }}</a>

</h3>
<p>Edit the entry</p>

<form action="{% url 'todolist:edit_entry' entry.id %}" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit"> add this item </button>


</form>

{% endblock content %}

todolist/templates/page/home.html
{% extends "page/base.html" %}
{% block content %}

<p> This is the home page !!!!</p>

{% endblock content %}

todolist/templates/page/new_entry.html
{% extends "page/base.html" %}
{% block content %}
<div class="container">
<h3>
    <a href="{% url 'todolist:single_todo_list' todolist.id %}">{{ todolist }}</a>

</h3>
<p>Add a new item to this list</p>

<form action="{% url 'todolist:new_entry' todolist.id %}" method="post">

    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit"> add this item </button>



</form>
</div>
{% endblock content %}

todolist/templates/page/new_topic.html
{% extends "page/base.html" %}
{% block content %}

<p> Add a new Topic to your TodoList </p>

<form action="{% url 'todolist:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit"> add this Topic </button>


</form>

{% endblock content %}

todolist/templates/page/original_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
<p>
    <a href="{% url 'todolist:todo' %}">All the todo lists</a>

</p>

{% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todolist/templates/page/single_todo_list.html
{% extends "page/base.html" %}
{% block content %}
<div class="container">
    <div>
    <br>
        <div class="col-lg-12 text-center" >
    <h2>{{ single_todo_list }}</h2>
        </div>
    <br>


    <ol>

        {% for item in items_to_that_list %}
        <br>
        <li >

    <form action="{% url 'todolist:single_todo_list' single_todo_list.id %}"  method="post">
        {% csrf_token %}
        <h5 class="bg-info">
        <input type="checkbox" name="item_id" id="{{ item.id }}" value="{{ item.id }}">
            {{ item.name }}
        </h5>
        <table class="table table-striped">
         <thead>
         <tr>
            <p>{{ item.description }}<br>
                Has this item been completed :  {{ item.done }}, <br>
                Due date: {{ item.due_date }}, <br>
                Days Left: {{ item.days_left }} days
            </p>

        <input type="submit" value="Completed">

        {% empty %}

        <li class="list-group-item d-flex justify-content-between align-items-center">
            There are no items for this List
        </li>

        {% endfor %}
    </form>

    </ol>


     </tr>
     </thead>
     </table>
    <br>


    </div>
<p class="text-center">
    <a class="btn btn-primary " href="{% url 'todolist:new_entry' single_todo_list.id %}">Add a new entry</a>
</p>

</div>




{% endblock content %}

todolist/templates/page/todo.html
{% extends "page/base.html" %}
{% block content %}


<div class="container">
    <br>
    <br>
    <h4>The TODO lists: </h4>
    <div class="container">

        <table class="table table-striped">
            <thead>

    <ul>

        {% for todo_list in complete_list %}

        <li><a href="{% url 'todolist:single_todo_list' todo_list.id %}">{{ todo_list.title }}</a></li>

        {% empty %}

            <li>No topics have been added yet.</li>

        {% endfor %}


    </ul>
            </thead>
        </table>

    </div>
    <div class="container">
     <a href="{% url 'todolist:new_topic' %}">Add a new Todo Topic on the List</a>
    </div>
</div>
{% endblock content %}

todolist/templates/page/working_base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Todo List</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">

      <a class="navbar-brand" href="#"> Todo List </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
           <li class="nav-item active">
            <a class="nav-link" href="{% url 'todolist:todo' %}">All the todo lists
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


          <!-- Page Content -->
            {% block content %}

            {% endblock content %}




  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>